### ISSUE TITLE
Merged PR's UI changes not reflecting in live link.

### ISSUE THREAD

**Issue by Prakash-Ravichandran** [ayusshh19/portfolio#14]
@ayusshh19 

Why the changes are not reflecting in the live link ?

**Comment by ravindercodes** [comment]
@Prakash-Ravichandran Merged PR's UI changes are not reflected in the live link because @ayusshh19 has not built the project with the new changes and deployed yet. There is not any automation to deploy the project. I think this the reason your changes are not reflected.
