### ISSUE TITLE
hamburger menu is not working

### ISSUE THREAD

**Issue by ashish07-07** [ayusshh19/portfolio#18]
https://github.com/ayusshh19/portfolio/assets/83639863/ef66a2f3-f933-4422-b109-0b4646d88169

**Comment by ayusshh19** [comment]
You can work on it remove that for desktop view @ashish07-07

**Comment by ashish07-07** [comment]
https://github.com/ayusshh19/portfolio/assets/83639863/75e80a95-6c23-44fc-b7ad-236f15ab83de

ya i have removed it for desktop view

**Comment by ashish07-07** [comment]
i have raised my pull request for the above i think its rejecting because of react version u are using it .

**Comment by Prakash-Ravichandran** [comment]
@ayusshh19 

Ayushh please correct the spelling of hacktoberfest.  K is missing in that. 
Also add hacktoberfest-accepted in my PR #10
