### ISSUE TITLE
links at the bottom are not working

### ISSUE THREAD

**Issue by ashish07-07** [ayusshh19/portfolio#21]
https://github.com/ayusshh19/portfolio/assets/83639863/185fa545-3672-4d29-b06e-a80c65ce6612

**Comment by ashish07-07** [comment]
can i work on this issue .

**Comment by ashish07-07** [comment]
ayush can  i work on this issue i have been working on this if u cauld assign me this issue so i can raise my pull request .

**Comment by ayusshh19** [comment]
@ashish07-07 sure you can !

**Comment by ashish07-07** [comment]
cauld you please  make it as hacktoberfest label  please .

**Comment by ashish07-07** [comment]
https://github.com/ayusshh19/portfolio/assets/83639863/f23016a4-c2c9-4404-ad7b-9a58e3a27885

I have made the corrections ,  please look at the PR raised

**Comment by ashish07-07** [comment]
hii ayuash can u plese go through the PR raised please .
