### ISSUE TITLE
[Feat] : Make Tech stack images of same size and beautify the UI

### ISSUE THREAD

**Issue by ayusshh19** [ayusshh19/portfolio#8]
Description : - 
Tech stack section images size looks variable and isnt looks good with grid

![08 10 2023_20 16 25_REC](https://github.com/ayusshh19/portfolio/assets/89308426/1c5d8f48-bed3-41c2-bdc0-17ccddd8c5f1)

**Comment by gaurab-khanal** [comment]
Can I work on this issue?

**Comment by ayusshh19** [comment]
@gaurab-khanal Sure !
