### ISSUE TITLE
committee cards UI to be made as attractive 

### ISSUE THREAD

**Issue by Prakash-Ravichandran** [ayusshh19/portfolio#9]
@ayusshh19 

assign this to me.

Before that please add hacktoberfest-accepted, hacktoberfest-2023 label in the repository's about also, if not or PR's are not accepted by hacktoberfest community.

Refere here.

![image](https://github.com/ayusshh19/portfolio/assets/74542543/d95d1dd9-808f-4821-b524-048f10be0870)

It shows not-accepted in hacktoberfest profile.

![image](https://github.com/ayusshh19/portfolio/assets/74542543/4e94ebaa-86fc-4df4-a8f8-07d8a1e49f7d)

**Comment by ayusshh19** [comment]
@Prakash-Ravichandran I have already added hacktoberfest label you have to use 'fix #"ISSUE NO"' to link your PR with the issue
